version: '2'
template:
  name: "Cloud Functions REST APIs Toolchain"
  description: "Deploy Serverless REST APIs"
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/IBM/ibm-cloud-functions-refarch-serverless-apis](https://github.com/IBM/ibm-cloud-functions-refarch-serverless-apis)
    git branch: >-
      [master](https://github.com/IBM/ibm-cloud-functions-refarch-serverless-apis/tree/master)
toolchain:
  name: 'cloud-functions-apis-toolchain'
services:
  repo:
    service_id: hostedgit
    parameters:
      repo_name: 'java-app-{{timestamp}}'
      repo_url: 'https://www.git.com/open-toolchain/java-spring-microservice'
      type: clone
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo1
          USERNAME: '{{form.pipeline.parameters.username}}'
          PASSWORD: '{{form.pipeline.parameters.password}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          SPACE: '{{form.pipeline.parameters.space}}'
          ORG: '{{form.pipeline.parameters.organization}}'
          REGION: '{{form.pipeline.parameters.region}}'
          GROUP: '{{form.pipeline.parameters.group}}'
        execute: true
form:
  pipeline:
    parameters:
    schema:
      $ref: deploy.json
